//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.BeetwenCarsClients = new HashSet<BeetwenCarsClients>();
        }
    
        public int IdCarModels { get; set; }
        public double Price { get; set; }
        public double Acceleration { get; set; }
        public int MaxSpeed { get; set; }
        public int YearOfIssue { get; set; }
        public string Image { get; set; }
        public string ImageAbove { get; set; }
        public Nullable<int> IdCarcassType { get; set; }
        public Nullable<int> IdColor { get; set; }
        public Nullable<int> IdModel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeetwenCarsClients> BeetwenCarsClients { get; set; }
        public virtual CarcassType CarcassType { get; set; }
        public virtual CarsModels CarsModels { get; set; }
        public virtual Color Color { get; set; }
    }
}
