//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalEntities : DbContext
    {
        public CarRentalEntities()
            : base("name=CarRentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeetwenCarsClients> BeetwenCarsClients { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<CarcassType> CarcassType { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<CarsModels> CarsModels { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
